/* tslint:disable */
/* eslint-disable */
/**
 * Articles Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ArticleQueryFilter,
  PageArticleList,
  PaginationFilter,
} from '../models/index';
import {
    ArticleQueryFilterFromJSON,
    ArticleQueryFilterToJSON,
    PageArticleListFromJSON,
    PageArticleListToJSON,
    PaginationFilterFromJSON,
    PaginationFilterToJSON,
} from '../models/index';

export interface GetAllArticleRequest {
    articleQueryFilterDto?: ArticleQueryFilter;
    paginationFilterDto?: PaginationFilter;
}

/**
 * ArticlesApi - interface
 * 
 * @export
 * @interface ArticlesApiInterface
 */
export interface ArticlesApiInterface {
    /**
     * Returns all articles
     * @param {ArticleQueryFilter} [articleQueryFilterDto] 
     * @param {PaginationFilter} [paginationFilterDto] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ArticlesApiInterface
     */
    getAllArticleRaw(requestParameters: GetAllArticleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PageArticleList>>;

    /**
     * Returns all articles
     */
    getAllArticle(requestParameters: GetAllArticleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PageArticleList>;

}

/**
 * 
 */
export class ArticlesApi extends runtime.BaseAPI implements ArticlesApiInterface {

    /**
     * Returns all articles
     */
    async getAllArticleRaw(requestParameters: GetAllArticleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PageArticleList>> {
        const queryParameters: any = {};

        if (requestParameters['articleQueryFilterDto'] != null) {
            queryParameters['articleQueryFilterDto'] = requestParameters['articleQueryFilterDto'];
        }

        if (requestParameters['paginationFilterDto'] != null) {
            queryParameters['paginationFilterDto'] = requestParameters['paginationFilterDto'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/articles`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PageArticleListFromJSON(jsonValue));
    }

    /**
     * Returns all articles
     */
    async getAllArticle(requestParameters: GetAllArticleRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PageArticleList> {
        const response = await this.getAllArticleRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
