/* tslint:disable */
/* eslint-disable */
/**
 * Articles Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Article
 */
export interface Article {
    /**
     * 
     * @type {Date}
     * @memberof Article
     */
    createdAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof Article
     */
    createdBy?: string;
    /**
     * 
     * @type {Date}
     * @memberof Article
     */
    updatedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof Article
     */
    updatedBy?: string;
    /**
     * 
     * @type {string}
     * @memberof Article
     */
    id?: string;
    /**
     * 
     * @type {boolean}
     * @memberof Article
     */
    deleted?: boolean;
}

/**
 * Check if a given object implements the Article interface.
 */
export function instanceOfArticle(value: object): value is Article {
    return true;
}

export function ArticleFromJSON(json: any): Article {
    return ArticleFromJSONTyped(json, false);
}

export function ArticleFromJSONTyped(json: any, ignoreDiscriminator: boolean): Article {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'createdBy': json['createdBy'] == null ? undefined : json['createdBy'],
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
        'updatedBy': json['updatedBy'] == null ? undefined : json['updatedBy'],
        'id': json['id'] == null ? undefined : json['id'],
        'deleted': json['deleted'] == null ? undefined : json['deleted'],
    };
}

export function ArticleToJSON(json: any): Article {
    return ArticleToJSONTyped(json, false);
}

export function ArticleToJSONTyped(value?: Article | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'createdBy': value['createdBy'],
        'updatedAt': value['updatedAt'] == null ? undefined : ((value['updatedAt']).toISOString()),
        'updatedBy': value['updatedBy'],
        'id': value['id'],
        'deleted': value['deleted'],
    };
}

