/* tslint:disable */
/* eslint-disable */
/**
 * Articles Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ArticleQueryFilter
 */
export interface ArticleQueryFilter {
    /**
     * 
     * @type {string}
     * @memberof ArticleQueryFilter
     */
    articleId?: string;
}

/**
 * Check if a given object implements the ArticleQueryFilter interface.
 */
export function instanceOfArticleQueryFilter(value: object): value is ArticleQueryFilter {
    return true;
}

export function ArticleQueryFilterFromJSON(json: any): ArticleQueryFilter {
    return ArticleQueryFilterFromJSONTyped(json, false);
}

export function ArticleQueryFilterFromJSONTyped(json: any, ignoreDiscriminator: boolean): ArticleQueryFilter {
    if (json == null) {
        return json;
    }
    return {
        
        'articleId': json['articleId'] == null ? undefined : json['articleId'],
    };
}

export function ArticleQueryFilterToJSON(json: any): ArticleQueryFilter {
    return ArticleQueryFilterToJSONTyped(json, false);
}

export function ArticleQueryFilterToJSONTyped(value?: ArticleQueryFilter | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'articleId': value['articleId'],
    };
}

