/* tslint:disable */
/* eslint-disable */
/**
 * Articles Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PageInfo
 */
export interface PageInfo {
    /**
     * 
     * @type {number}
     * @memberof PageInfo
     */
    pageSize?: number;
    /**
     * First page number: 0
     * @type {number}
     * @memberof PageInfo
     */
    pageNumber?: number;
    /**
     * Null if no previous page available
     * @type {string}
     * @memberof PageInfo
     */
    previousPage?: string;
    /**
     * Null if no next page available
     * @type {string}
     * @memberof PageInfo
     */
    nextPage?: string;
    /**
     * 
     * @type {number}
     * @memberof PageInfo
     */
    itemsTotal?: number;
    /**
     * 
     * @type {number}
     * @memberof PageInfo
     */
    pagesTotal?: number;
}

/**
 * Check if a given object implements the PageInfo interface.
 */
export function instanceOfPageInfo(value: object): value is PageInfo {
    return true;
}

export function PageInfoFromJSON(json: any): PageInfo {
    return PageInfoFromJSONTyped(json, false);
}

export function PageInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'pageSize': json['pageSize'] == null ? undefined : json['pageSize'],
        'pageNumber': json['pageNumber'] == null ? undefined : json['pageNumber'],
        'previousPage': json['previousPage'] == null ? undefined : json['previousPage'],
        'nextPage': json['nextPage'] == null ? undefined : json['nextPage'],
        'itemsTotal': json['itemsTotal'] == null ? undefined : json['itemsTotal'],
        'pagesTotal': json['pagesTotal'] == null ? undefined : json['pagesTotal'],
    };
}

export function PageInfoToJSON(json: any): PageInfo {
    return PageInfoToJSONTyped(json, false);
}

export function PageInfoToJSONTyped(value?: PageInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'pageSize': value['pageSize'],
        'pageNumber': value['pageNumber'],
        'previousPage': value['previousPage'],
        'nextPage': value['nextPage'],
        'itemsTotal': value['itemsTotal'],
        'pagesTotal': value['pagesTotal'],
    };
}

