/* tslint:disable */
/* eslint-disable */
/**
 * Articles Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Article } from './Article';
import {
    ArticleFromJSON,
    ArticleFromJSONTyped,
    ArticleToJSON,
    ArticleToJSONTyped,
} from './Article';

/**
 * 
 * @export
 * @interface PageArticleList
 */
export interface PageArticleList {
    /**
     * 
     * @type {number}
     * @memberof PageArticleList
     */
    pageSize?: number;
    /**
     * First page number: 0
     * @type {number}
     * @memberof PageArticleList
     */
    pageNumber?: number;
    /**
     * Null if no previous page available
     * @type {string}
     * @memberof PageArticleList
     */
    previousPage?: string;
    /**
     * Null if no next page available
     * @type {string}
     * @memberof PageArticleList
     */
    nextPage?: string;
    /**
     * 
     * @type {number}
     * @memberof PageArticleList
     */
    itemsTotal?: number;
    /**
     * 
     * @type {number}
     * @memberof PageArticleList
     */
    pagesTotal?: number;
    /**
     * 
     * @type {Array<Article>}
     * @memberof PageArticleList
     */
    data?: Array<Article>;
}

/**
 * Check if a given object implements the PageArticleList interface.
 */
export function instanceOfPageArticleList(value: object): value is PageArticleList {
    return true;
}

export function PageArticleListFromJSON(json: any): PageArticleList {
    return PageArticleListFromJSONTyped(json, false);
}

export function PageArticleListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageArticleList {
    if (json == null) {
        return json;
    }
    return {
        
        'pageSize': json['pageSize'] == null ? undefined : json['pageSize'],
        'pageNumber': json['pageNumber'] == null ? undefined : json['pageNumber'],
        'previousPage': json['previousPage'] == null ? undefined : json['previousPage'],
        'nextPage': json['nextPage'] == null ? undefined : json['nextPage'],
        'itemsTotal': json['itemsTotal'] == null ? undefined : json['itemsTotal'],
        'pagesTotal': json['pagesTotal'] == null ? undefined : json['pagesTotal'],
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(ArticleFromJSON)),
    };
}

export function PageArticleListToJSON(json: any): PageArticleList {
    return PageArticleListToJSONTyped(json, false);
}

export function PageArticleListToJSONTyped(value?: PageArticleList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'pageSize': value['pageSize'],
        'pageNumber': value['pageNumber'],
        'previousPage': value['previousPage'],
        'nextPage': value['nextPage'],
        'itemsTotal': value['itemsTotal'],
        'pagesTotal': value['pagesTotal'],
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(ArticleToJSON)),
    };
}

