/* tslint:disable */
/* eslint-disable */
/**
 * Articles Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PaginationFilter
 */
export interface PaginationFilter {
    /**
     * 
     * @type {number}
     * @memberof PaginationFilter
     */
    pageSize?: number;
    /**
     * 
     * @type {number}
     * @memberof PaginationFilter
     */
    pageNumber?: number;
}

/**
 * Check if a given object implements the PaginationFilter interface.
 */
export function instanceOfPaginationFilter(value: object): value is PaginationFilter {
    return true;
}

export function PaginationFilterFromJSON(json: any): PaginationFilter {
    return PaginationFilterFromJSONTyped(json, false);
}

export function PaginationFilterFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginationFilter {
    if (json == null) {
        return json;
    }
    return {
        
        'pageSize': json['pageSize'] == null ? undefined : json['pageSize'],
        'pageNumber': json['pageNumber'] == null ? undefined : json['pageNumber'],
    };
}

export function PaginationFilterToJSON(json: any): PaginationFilter {
    return PaginationFilterToJSONTyped(json, false);
}

export function PaginationFilterToJSONTyped(value?: PaginationFilter | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'pageSize': value['pageSize'],
        'pageNumber': value['pageNumber'],
    };
}

