/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Articles Api
 * OpenAPI spec version: 1.0.0
 */
import { Hono } from 'hono';
import {

} from './api-eafs/generated/endpoints/articles/articles.handlers';

const app = new Hono()

app.get('/api/v1/articles',...getAllArticleHandlers)

export default app
